GALI-SPINAL TUBE
Version 4 – TiC + PTFE, Sphere-Size Scaling
Technical Specification Sheet
Date: 06 April 2026
Designer / Concept Origin: J.Vandamn
1. Overview
The Gali-Spinal Tube is a vertical, sealed magneto-sonic resonance column designed for continuous fluid-dynamic energy transfer and targeted molecular-scale effects. It combines high-performance advanced materials, liquid-metal carrier fluid, size-scaled magnetite resonators, and dual-frequency sonic heads to create a driven, high-RPM whipping motion within a Lorentz-force augmented field.
The system produces two distinct output regimes:
•  Energy Head – aggressive, high-frequency ionizing output
•  Molecular Healing Head – gentler, restorative de-ionizing coherence
Intended applications include advanced materials research, sonochemical processing, and speculative molecular-healing / coherence studies.
2. Physical Construction
•  Overall Dimensions: 380 mm height × 65 mm diameter (side-view tube)
•  Outer Structural Wall: Titanium Carbide (TiC) – ultra-high hardness (HV 2800–3200), exceptional wear resistance under high RPM and sonic threshold pressure
•  Inner Lining: PTFE (polytetrafluoroethylene) – chemically inert, ultra-low friction surface for sphere transit
•  Sealing: Double-headed sleeved ferrite at base with pure-iron magnetic return path on one flank
•  Carrier Fluid: 40 % DMSO + Galinstan (room-temperature liquid metal alloy) – optional deionized-water variant for lower conductivity tuning
3. Active Elements
•  Resonator Spheres: Highly purified magnetite (Fe₃O₄) spheres
	•  Size-scaled vertically (2 mm base → 8 mm top) for progressive mass increase, stronger centrifugal contribution, and richer MHz harmonic spectrum
	•  Color code: black / blue dots
•  Ionizing / De-ionizing Nodes
	•  Yellow = ionizing node (sharp-angle, high-frequency)
	•  Green = de-ionizing node (soft-angle, restorative)
•  Mercurial Reference Points: Red accents (mercury-channel notes for plasma / hydrogen atmosphere studies)
4. Operating Principles
•  Primary Drive: Lorentz forces generated by external ferrite field interacting with conductive Galinstan carrier under high-RPM centrifugal “whip” motion
•  Sonic Regime: Dual MHz resonance bands (energy head: sharp, aggressive high-frequency “song”; healing head: softer green-blue pulsing with restorative coherence glow at sonic crossover)
•  Fluid Dynamics: Spheres whip in perpetual-like closed-loop motion through the blue carrier fluid, producing centrifugal force, cavitation nuclei, and harmonic pressure waves
•  Energy Transfer: “Other side” pure-iron magnetic return path completes the circuit; sonic threshold “snap zone” at mid-column creates visible plasma-like coherence effects
Note: System is externally driven (pulsed electromagnetic coil + ultrasonic transducer at base) to maintain stable operation; true closed-loop efficiency is under ongoing optimization.