.github/workflows/markdown-lint.yml
name: TOC Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generateTOC:
    name: Generate Table of Contents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOC_TITLE: '## Table of Contents'
          FOLDING: false
          MAX_HEADER_LEVEL: 3